### ISSUE TITLE
spark migrate does not work if DBPrefix defned

### ISSUE THREAD

**Issue by mshannaq** [Extendy/SmartyURL#28]
if config variable DBPrefix or .env vairable DBPrefix is defined so php spark migrate will not work and wil give

```
CodeIgniter v4.4.1 Command Line Tool - Server Time: 2023-09-25 14:32:43 UTC+00:00

Running all new migrations...

[CodeIgniter\Database\Exceptions\DatabaseException]
```
migration should be changed to support DBPrefix

**Comment by extendy-sam** [comment]
UrlModel should be reviewed and changed
and migration script should be reviews to make sure from using table names from Config files.

becuase it DBPrefix changes will break that.

**Comment by mshannaq** [comment]
do not use `DBPrefix` in .env 

and keep it the DBPrefix as default 

` 'DBPrefix'     => '',`
