### ISSUE TITLE
rate limit notice

### ISSUE THREAD

**Issue by extendy-sam** [Extendy/SmartyURL#36]
I've noticed the presence of a rate-limit across all SmartyURL, which is undoubtedly beneficial for safeguarding URL Go Controller and URL identifiers.

However, it appears that when we utilize 10 requests, the rate limit affects regular users (error 429 appear to me when using Add New URL). Would it be possible to increase the rate limit for all site-related activities while retaining it at 10 for user login forms and Go controller, without the need for a shield core change?

If this isn't possible, could we consider applying the rate-limit exclusively to the URL Go controller and shield only, and removing the rate limit for all other requests?

Your insights and guidance on this matter would be greatly appreciated.

**Comment by mshannaq** [comment]
@extendy-sam  We must check the default settings of the ci to check the ability.

**Comment by mshannaq** [comment]
Take a look into https://www.codeigniter.com/user_guide/libraries/throttler.html
