### ISSUE TITLE
duplicated tag in tags cloud

### ISSUE THREAD

**Issue by extendy-sam** [Extendy/SmartyURL#43]
in New URL form when showing tags cloud and if `urltags_shared_between_users` set to `true` then if there is same tag name for more than one user then the tag cloud shown duplicated tags:

**See:**
![image](https://github.com/Extendy/SmartyURL/assets/146824708/9aeebbd0-5c0c-4c49-b854-d6041ea2d660)

While this isn't problematic as each tag has its unique id, we should enhance performance by displaying only one tag, eliminating duplicates.

**Comment by mshannaq** [comment]
but to do that I use 2 db query in `src/UtrlTags::getUserUrlTagsCloud` which i think is not best for performance:

I did this in order to check for duplicates among tags. If there is a duplication, I prioritize using tags that are primarily associated with the user instead of other users tags.
