### ISSUE TITLE
URL identifier unique ?

### ISSUE THREAD

**Issue by extendy-sam** [Extendy/SmartyURL#50]
Are URL identifiers case-sensitive? For example, are the following two identifiers the same:

`secure_wordpress`
`secure_WORDPRESS`
If they are different, then this could lead to problems if two users try to create resources with the same identifier, but different cases.

**Comment by mshannaq** [comment]
The Url is not cas sensitive, so `secure_wordpress` & `secure_WORDPRESS` is the same and can be used once.

This is due the database record becuase `url_identifier` columns is **Unique**
