### ISSUE TITLE
is there any option to add favicon?

### ISSUE THREAD

**Issue by extendy-sam** [Extendy/SmartyURL#54]
is there any option to add favicon? or it out of scope?

**Comment by mshannaq** [comment]
I removed the favicon.ico in commit 96713e067752fb4888ee68b12e8f5156eddbd652

@extendy-sam  could you please check in in the next live test.

Thanks

**Comment by mshannaq** [comment]
We removed the default favicon.

**Comment by mshannaq** [comment]
I think is is out of scope
