### ISSUE TITLE
QR code generator for URL

### ISSUE THREAD

**Issue by mshannaq** [Extendy/SmartyURL#78]
We should explore open-source tools for generating QR codes for URLs. The selected tool should offer the following capabilities:

- The tool must be capable of generating PNG or SVG QR codes in various sizes (SVG Preferred). 
- It would be advantageous if we could have control over the appearance of the generated QR code, allowing customization such as changing colors and, if possible, adding images to it.
- While it's not a requirement, it would be advantageous if the tool could also generate QR codes in PDF format.

**Note that:**
When generating a QR code for a URL, it's essential to include a query string segment to track visits originating from the QR code.

## Why yo generate QR Code for every URL

Generating a QR code for every shortened URL in SmartyURL can be a valuable feature for several reasons:

1. **Accessibility and Convenience**: QR codes provide a convenient way for users to quickly access the shortened URL, especially on mobile devices. Users can scan the code instead of manually typing the URL.

2. **Enhanced User Experience**: Offering QR codes can enhance the user experience, making it easier for people to interact with the URLs you've shortened. This can be particularly beneficial for marketing campaigns, where users may need to access URLs on physical materials (e.g., posters, flyers).

3. **Tracking and Analytics**: If SmartyURL generates unique QR codes for each shortened URL, it can also track and provide analytics on QR code scans. This data can be valuable for businesses and marketers to measure the effectiveness of their campaigns.

4. **Sharing and Distribution**: QR codes simplify the process of sharing URLs. Users can easily share URLs by sharing the QR code image, which can be embedded in print materials, presentations, or online content.

5. **Promotional Use**: For businesses, QR codes can be used in promotional materials, linking customers to special offers, product details, or loyalty programs. This can increase customer engagement and conversions.

6. **Multi-Platform Compatibility**: QR codes are widely supported on various devices and platforms, making them accessible to a broad audience.

7. **Branding and Customization**: SmartyURL can provide options for customizing QR codes with branding elements, such as logos or colors, to align with a company's visual identity.

Overall, integrating QR code generation into SmartyURL can improve accessibility, user experience, and analytics, making it a valuable feature for both individual users and businesses. It's a versatile tool that can be used in various scenarios to simplify URL sharing and tracking.

**Comment by mshannaq** [comment]
PHP libraries to consider (**testing required**):

- **BaconQrCode** (GitHub: [Bacon/BaconQrCode](https://github.com/Bacon/BaconQrCode)): A QR code encoder based on the QR code portion of the ZXing library. Currently, it provides encoding functionality and may include decoding capabilities in the future.

- **php-qrcode** (GitHub: [chillerlan/php-qrcode](https://github.com/chillerlan/php-qrcode)): A PHP QR code generator inspired by the implementation by Kazuhiko Arase. It's namespaced, enhanced, and features a QR code reader based on a PHP port of the ZXing library.

**Comment by mshannaq** [comment]
Visit https://github.com/kenjis/ci4-qrcode to review @kenjis work and gain insights into the fundamentals. It appears that he utilized https://github.com/dwisetiyadi/CodeIgniter-PHP-QR-Code, a project that hasn't been actively maintained for over eight years

**Comment by mshannaq** [comment]
I've tested https://github.com/chillerlan/php-qrcode, and it appears to work well. I was able to create a QR code like the one shown here:

![QR Code](https://github.com/Extendy/SmartyURL/assets/162535/e02937e7-5e7f-46f2-a51c-5c236bb1ff96)

However, please note that to access all the features described in the php-qrcode documentation, you should use `composer require chillerlan/php-qrcode:dev-main` instead of `composer require chillerlan/php-qrcode`.

I vote to use @codemasher chillerlan/php-qrcode library in this project

**Comment by extendy-sam** [comment]
> I've tested https://github.com/chillerlan/php-qrcode, and it appears to work well. I was able to create a QR code like the one shown here:
> 
> ![QR Code](https://user-images.githubusercontent.com/162535/280161325-e02937e7-5e7f-46f2-a51c-5c236bb1ff96.png)
> 
> However, please note that to access all the features described in the php-qrcode documentation, you should use `composer require chillerlan/php-qrcode:dev-main` instead of `composer require chillerlan/php-qrcode`.
> 
> I vote to use @codemasher chillerlan/php-qrcode library in this project

You can test [chillerlan/php-qrcode](https://github.com/chillerlan/php-qrcode) online using https://smiley.codes/qrcode/ which is available [over here on GitHub](https://github.com/codemasher/nova-qrcode)

**Comment by codemasher** [comment]
> However, please note that to access all the features described in the php-qrcode documentation, you should use `composer require chillerlan/php-qrcode:dev-main` instead of `composer require chillerlan/php-qrcode`.

Hi! Since you pinged me here I just popped in to let you know that I'm preparing the 5.0 release and I hope to get it out in the next few weeks! Feel free to [open a discussion](https://github.com/chillerlan/php-qrcode/discussions) if you have any questions or need help.

**Comment by mshannaq** [comment]
> > However, please note that to access all the features described in the php-qrcode documentation, you should use `composer require chillerlan/php-qrcode:dev-main` instead of `composer require chillerlan/php-qrcode`.
> 
> Hi! Since you pinged me here I just popped in to let you know that I'm preparing the 5.0 release and I hope to get it out in the next few weeks! Feel free to [open a discussion](https://github.com/chillerlan/php-qrcode/discussions) if you have any questions or need help.

Thanks so much for your reply! We really appreciate it. I will be sure to keep a close watch on the 'chillerlan/php-qrcode' GitHub repository. When you release v5.0, we'll happily update our project configuration to use it, rather than 'dev-main'. 😊
